export * from './vehicle-base-input.dto';
export * from './vehicle-base-output.dto';
export * from './create-one-vehicle-input.dto';
export * from './create-one-vehicle-output.dto';
export * from './update-one-vehicle-input.dto';
export * from './update-one-vehicle-output.dto';
export * from './get-one-vehicle-output.dto';
export * from './get-many-vehicle-output.dto';
export * from './delete-one-vehicle-output.dto';
